---
- name: Uninstall .NET SDK from Windows
  hosts: windows
  connection: winrm
  tasks:
    - name: Check if .NET SDK is installed
      ansible.windows.win_command: dotnet --version
      register: dotnet_version
      ignore_errors: yes

    - name: Remove .NET SDK if installed
      ansible.windows.win_command:
        cmd: "dotnet --uninstall"
      when: dotnet_version.rc == 0

    - name: Delete .NET SDK installer
      ansible.windows.win_file:
        path: C:\temp\dotnet-sdk-installer.exe
        state: absent

    - name: Remove temp directory
      ansible.windows.win_file:
        path: C:\temp
        state: absent
