---
- name: Delete shortcut on Windows
  hosts: windows
  connection: winrm
  tasks:
    - name: Delete the shortcut
      ansible.windows.win_file:
        path: C:\Users\ansible\Desktop\test_shortcut.lnk
        state: absent
