---
- name: Install or Update .NET on Windows
  hosts: windows
  connection: winrm
  tasks:
    - name: Create temp directory if it doesn't exist
      ansible.windows.win_file:
        path: C:\temp
        state: directory

    - name: Remove existing .NET installer if it exists
      ansible.windows.win_file:
        path: C:\temp\dotnet-sdk-installer.exe
        state: absent

    - name: Download .NET SDK installer
      ansible.windows.win_get_url:
        url: https://aka.ms/install-dotnet
        dest: C:\temp\dotnet-sdk-installer.exe

    - name: Check if .NET SDK is installed
      ansible.windows.win_command: "dotnet --version"
      register: dotnet_version
      ignore_errors: yes

    - name: Force reinstall the .NET SDK to update
      ansible.windows.win_powershell:
        script: |
          Start-Process "C:\temp\dotnet-sdk-installer.exe" -ArgumentList "/quiet /norestart /force" -Wait -PassThru
      when: dotnet_version.failed  # Only run the installer if dotnet is not installed, or if an update is needed

    - name: Ensure .NET SDK is updated
      ansible.windows.win_powershell:
        script: |
          Start-Process "C:\temp\dotnet-sdk-installer.exe" -ArgumentList "/quiet /norestart /force" -Wait -PassThru
      when: dotnet_version.stdout is search("No SDKs installed")
