- name: Install Chocolatey on Windows
  hosts: windows
  tasks:
    - name: Install Chocolatey package manager
      win_chocolatey:
        name: chocolatey
        state: present
    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present
