---
- name: Install or Update .NET on Windows
  hosts: windows
  connection: winrm
  tasks:
    - name: Create temp directory if it doesn't exist
      ansible.windows.win_file:
        path: C:\temp
        state: directory

    - name: Remove existing .NET installer if it exists
      ansible.windows.win_file:
        path: C:\temp\dotnet-sdk-installer.exe
        state: absent

    - name: Download .NET SDK installer
      ansible.windows.win_get_url:
        url: https://aka.ms/install-dotnet
        dest: C:\temp\dotnet-sdk-installer.exe

    - name: Run PowerShell script to install .NET SDK
      ansible.windows.win_powershell:
        script: |
          Start-Process "C:\temp\dotnet-sdk-installer.exe" -ArgumentList "/quiet /norestart" -Wait -PassThru
