---
- name: Install or Update .NET on Windows
  hosts: windows
  connection: winrm
  tasks:
    - name: Create temp directory if it doesn't exist
      ansible.windows.win_file:
        path: C:\temp
        state: directory

    - name: Download .NET SDK installer
      ansible.windows.win_get_url:
        url: https://aka.ms/install-dotnet
        dest: C:\temp\dotnet-sdk-installer.exe

    - name: Check if the .NET SDK installer exists
      ansible.windows.win_stat:
        path: C:\temp\dotnet-sdk-installer.exe
      register: file_stat

    - name: Install or Update .NET SDK
      ansible.windows.win_package:
        path: C:\temp\dotnet-sdk-installer.exe
        product_id: dotnet-sdk
        state: present
        arguments: '/quiet /norestart'
      when: file_stat.stat.exists
