- name: Install netstat on Ubuntu
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install net-tools (includes netstat)
      apt:
        name: net-tools
        state: present
