---
- name: Set Windows File Explorer to show hidden files
  hosts: windows
  tasks:
    - name: Set registry value for Hidden files
      win_registry:
        path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
        name: 'Hidden'
        data: '1'
        type: dword
        state: present
