---
- name: Set Windows to show file extensions
  hosts: windows
  tasks:
    - name: Ensure the registry path exists
      win_shell: |
        if (-not (Test-Path 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced')) {
          New-Item -Path 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced' -Force
        }

    - name: Set registry value to show file extensions
      win_shell: |
        Set-ItemProperty -Path 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced' -Name 'HideFileExt' -Value 0
      ignore_errors: yes
