---
- name: Set Windows File Explorer to show hidden files
  hosts: windows
  tasks:
    - name: Set registry value using PowerShell
      win_shell: |
        Set-ItemProperty -Path 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced' -Name 'Hidden' -Value 1 -Type DWord
