- name: Configure Google Chrome to force a specific homepage on startup
  hosts: windows
  tasks:
    - name: Set Chrome Homepage URL
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Google\Chrome
        name: HomepageLocation
        data: "https://www.google.com"
        type: string
        state: present

    - name: Enforce Chrome to show homepage on startup
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Google\Chrome
        name: RestoreOnStartup
        data: 1
        type: dword
        state: present

    - name: Disable the New Tab page on startup
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Google\Chrome
        name: NewTabPageLocation
        state: absent

    - name: Force Google Chrome to apply mandatory policies
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Google\Chrome
        name: BrowserSignin
        data: 0
        type: dword
        state: present
