- name: Configure Google Chrome to force a specific homepage on startup
  hosts: windows
  tasks:
  - name: Set Chrome Homepage Policy at User Level
    ansible.windows.win_regedit:
      path: HKCU:\Software\Policies\Google\Chrome
      name: HomepageLocation
      data: "https://www.google.com"
      type: string
      state: present
  
  - name: Enforce Chrome Startup Behavior at User Level
    ansible.windows.win_regedit:
      path: HKCU:\Software\Policies\Google\Chrome
      name: RestoreOnStartup
      data: 1
      type: dword
      state: present
