---
- name: Set Windows to show file extensions
  hosts: windows
  tasks:
    - name: Ensure the registry path exists
      win_regedit:
        path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
        state: present

    - name: Set registry value to show file extensions
      win_registry:
        path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
        name: 'HideFileExt'
        data: '0'
        type: dword
