- name: Configure Google Chrome Registry Settings
  hosts: windows
  tasks:
    - name: Enable Chrome Auto-Update
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Google\Update
        name: AutoUpdateCheckPeriodMinutes
        data: 1440
        type: dword
        state: present

    - name: Set Chrome Homepage URL
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Google\Chrome
        name: HomepageLocation
        data: "https://www.google.com"
        type: string
        state: present

    - name: Set Chrome to open the homepage on startup
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Google\Chrome
        name: RestoreOnStartup
        data: 1
        type: dword
        state: present

    - name: Disable Chrome Password Manager
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Google\Chrome
        name: PasswordManagerEnabled
        data: 0
        type: dword
        state: present
