---
- name: Set Windows File Explorer to show hidden files
  hosts: windows
  tasks:
    - name: Check if the registry path exists
      win_regedit:
        path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
        state: directory
      register: reg_path_check

    - name: Create the registry path if it doesn't exist
      win_regedit:
        path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
        state: directory
      when: reg_path_check.failed

    - name: Set registry value using PowerShell
      win_shell: |
        Set-ItemProperty -Path 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced' -Name 'Hidden' -Value 1
      when: reg_path_check.changed
