---
- name: Set Windows to show file extensions
  hosts: windows
  tasks:
    - name: Ensure the registry path exists
      win_registry:
        path: HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: HideFileExt
        state: present
        type: dword
        value: 0
