---
- name: Set Windows File Explorer to show hidden files
  hosts: windows
  tasks:
    - name: Ensure the registry path exists
      win_regedit:
        path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
        state: present

    - name: Set registry value to show hidden files
      win_shell: |
        Set-ItemProperty -Path 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced' -Name 'Hidden' -Value 1
