---
- name: Set Windows File Explorer to show hidden files
  hosts: windows
  tasks:
    - name: Set the registry key to show hidden files
      win_regedit:
        path: 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced'
        name: 'Hidden'
        data: '1'  # '1' shows hidden files, '2' hides them
        type: dword
        state: present
