---
- name: Set Registry Keys to Show Hidden Files and Folders
  hosts: windows
  tasks:
    - name: Set Registry Keys to Show Hidden Files and Folders
      ansible.windows.win_registry:
        path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
        name: 'Hidden'
        data: 1
        type: dword
        state: present

    - name: Set Registry Key to Show Protected Operating System Files
      ansible.windows.win_registry:
        path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
        name: 'ShowSuperHidden'
        data: 1
        type: dword
        state: present
