---
- name: Copy file to desktop and create service
  hosts: windows
  tasks:
    - name: Copy test.exe to the desktop
      ansible.windows.win_copy:
        src: "C:\\path_to_local\\test.exe"  # Path to your local test.exe file
        dest: "C:\\Users\\ansible\\Desktop\\test.exe"  # Destination path on the target machine

    - name: Create service MyService
      ansible.windows.win_service:
        name: MyService
        path: "C:\\Users\\ansible\\Desktop\\test.exe"  # Ensure the path is correctly quoted
        display_name: "Service Name"
        description: "A test service description"
        start_mode: auto  # Set the service to start automatically
        state: started  # Ensure the service is started
