- name: Change the start mode of MyService to Manual
  hosts: windows
  tasks:
    - name: Update the Start value in the registry
      ansible.windows.win_regedit:
        path: HKLM\SYSTEM\CurrentControlSet\Services\MyService
        name: Start
        value: 3  # 3 = Manual, 2 = Automatic, 4 = Disabled
        type: dword
