- name: Check HideFileExt registry key value
  hosts: windows
  tasks:
    - name: Get Registry Value
      ansible.windows.win_reg_stat:
        path: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
        name: HideFileExt
      register: reg_value

    - name: Debug Registry Value
      ansible.builtin.debug:
        msg: "HideFileExt is set to {{ reg_value.value }}"
