---
- name: Set Registry Keys to Show Hidden Files and Folders
  hosts: windows
  tasks:
    - name: Set Registry Keys to Show Hidden Files and Folders
      win_shell: |
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "Hidden" -Value 1 -Type DWord

    - name: Set Registry Key to Show Protected Operating System Files
      win_shell: |
        Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "ShowSuperHidden" -Value 1 -Type DWord
