- name: Change the start mode of MyService to Manual
  hosts: windows
  tasks:
    - name: Update the Start value in the registry
      ansible.windows.win_regedit:
        path: HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: HideFileExt
        value: 1  # 3 = Manual, 2 = Automatic, 4 = Disabled
        type: dword
