---
- name: Configure Windows Defender Antivirus settings
  hosts: windows
  collections:
    - ansible.windows
  tasks:
    - name: Ensure Windows Defender Antivirus is enabled
      win_service:
        name: WinDefend
        state: started
        start_mode: auto

    - name: Add folder exclusion to Windows Defender
      win_command: |
        powershell -Command Add-MpPreference -ExclusionPath "C:\Users\ansible\Desktop\defender"
    
    - name: Add file exclusion to Windows Defender (if needed)
      win_command: |
        powershell -Command Add-MpPreference -ExclusionProcess "C:\path\to\file.exe"  # Replace with your file path
    
    - name: Add process exclusion to Windows Defender (if needed)
      win_command: |
        powershell -Command Add-MpPreference -ExclusionProcess "process_name.exe"  # Replace with actual process

    - name: Ensure Windows Defender Antivirus is enabled with recommended settings
      ansible.windows.win_registry:
        path: 'HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection'
        name: DisableRealtimeMonitoring
        data: 0
        type: dword
        state: present
