- name: Modify Windows Registry Key
  hosts: windows
  tasks:
    - name: Update the HideFileExt registry value
      ansible.windows.win_regedit:
        path: "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\\Advanced"
        name: HideFileExt
        value: 0
        type: dword
