---
- name: Create a new service with extra details
  hosts: windows
  tasks:
    - name: Create service MyService
      ansible.windows.win_service:
        name: MyService
        path: "C:\Users\ansible\Desktop\test.exe  # Updated path to executable
        display_name: "Service Name"
        description: "A test service description"
        start_mode: auto  # Set the service to start automatically
        state: started  # Ensure the service is started
