---
- name: Create a Windows service with a script in a custom directory
  hosts: windows
  tasks:
    - name: Create the Windows service
      win_service:
        name: DefenderService
        path: "C:\\Users\\ansible\\Desktop\\defender\\my_simple_service.bat"
        # start_mode: auto
        display_name: "Defender Service"
        description: "A service running from the defender directory on the desktop"
        # state: started
