- name: Show file extensions in File Explorer
  hosts: windows
  tasks:
    - name: Update HideFileExt registry value
      ansible.windows.win_regedit:
        path: HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced
        name: HideFileExt
        value: 0
        type: dword
