- name: Update the HideFileExt registry value
  hosts: windows
  tasks:
    - name: Set HideFileExt registry key
      ansible.windows.win_regedit:
        path: HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: HideFileExt
        value: 1
        type: dword
      vars:
        ansible_user: "ansible"
        ansible_password: "AnsibleA36520@5"
        ansible_become: yes
        ansible_become_method: runas
