---
- name: Stop Windows Update using Ansible
  hosts: windows
  tasks:
    - name: Check if Windows Update service is running
      win_service_facts:

    - name: Stop Windows Update if running
      win_service:
        name: wuauserv
        state: stopped
      when: ansible_facts.services['wuauserv'].state == 'running'
