---
- name: Install or Update .NET SDK on Windows
  hosts: windows
  connection: winrm
  tasks:
    - name: Check if .NET is in PATH
      ansible.windows.win_command: "where.exe dotnet"
      register: dotnet_path_check
      ignore_errors: yes

    - name: Install .NET SDK if not found
      ansible.windows.win_powershell:
        script: |
          Write-Output "Running installer"
          Start-Process "C:\temp\dotnet-sdk-installer.exe" -ArgumentList "/quiet /norestart /force" -Wait -PassThru
      when: dotnet_path_check.rc != 0

    - name: Manually add dotnet to PATH (if not found)
      ansible.windows.win_environment:
        name: PATH
        value: "C:\Program Files\dotnet"
        state: present
      when: dotnet_path_check.rc != 0

    - name: Verify .NET SDK installation
      ansible.windows.win_command: "dotnet --version"
      register: dotnet_version
      ignore_errors: yes

    - name: Debug .NET SDK installation result
      ansible.builtin.debug:
        var: dotnet_version.stdout
