- name: Update the HideFileExt registry value
  hosts: windows
  tasks:
    - name: Set HideFileExt registry key
      ansible.windows.win_regedit:
        path: HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: HideFileExt
        value: 1
        type: dword
