- name: Set HideFileExt registry key to 1
  hosts: windows
  tasks:
    - name: Modify registry key to 1
      ansible.windows.win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: HideFileExt
        value: 1
        type: dword
        state: present

    - name: Get Registry Value
      ansible.windows.win_reg_stat:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: HideFileExt
      register: reg_value

    - name: Print Registry Value
      ansible.builtin.debug:
        msg: "HideFileExt is set to {{ reg_value.value }}"
