- name: Set Mouse Pointer Speed
  hosts: windows
  tasks:
    - name: Modify Mouse Sensitivity
      ansible.windows.win_regedit:
        path: "HKCU:\\Control Panel\\Mouse"
        name: MouseSensitivity
        value: "15"  # Ensure it's a string
        type: string
        state: present

    - name: Get Registry Value
      ansible.windows.win_reg_stat:
        path: "HKCU:\\Control Panel\\Mouse"
        name: MouseSensitivity
      register: reg_value

    - name: Print Registry Value
      ansible.builtin.debug:
        msg: "MouseSensitivity is set to {{ reg_value.value }}"
