- name: Set Mouse Pointer Speed
  hosts: windows
  tasks:
    - name: Disable keyboard layout hotkey for all users (changes existing)
      ansible.windows.win_regedit:
        path: HKU:\.DEFAULT\Keyboard Layout\Toggle
        name: Layout Hotkey
        data: 3
        type: dword

    - name: Get Registry Value
      ansible.windows.win_reg_stat:
        path: HKU:\.DEFAULT\Keyboard Layout\Toggle
        name: Layout Hotkey
      register: reg_value

    - name: Print Registry Value
      ansible.builtin.debug:
        msg: "MouseSensitivity is set to {{ reg_value.value }}"
