---
- name: Disable firewall on Windows
  hosts: windows
  collections:
    - ansible.windows
  tasks:
    - name: Disable firewall
      win_firewall:
        state: enabled
        profiles:
          - Private
          - Public
